"""add profile_image to user

Revision ID: 140c8235b57a
Revises: 4d0a7801298e
Create Date: 2025-07-17 17:37:51.114713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140c8235b57a'
down_revision = '4d0a7801298e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
