"""Add outfit_id to Like

Revision ID: 1f92de989de6
Revises: 8063b62b2ee5
Create Date: 2025-07-04 20:13:22.395920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f92de989de6'
down_revision = '8063b62b2ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outfit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'outfits', ['outfit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('outfit_id')

    # ### end Alembic commands ###
