"""Add embedding fields to WardrobeItem

Revision ID: a3b4338b0597
Revises: e741b9d40a90
Create Date: 2025-09-04 21:56:27.660821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b4338b0597'
down_revision = 'e741b9d40a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wardrobe_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_embedding', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('text_embedding', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('combined_embedding', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wardrobe_item', schema=None) as batch_op:
        batch_op.drop_column('combined_embedding')
        batch_op.drop_column('text_embedding')
        batch_op.drop_column('image_embedding')

    # ### end Alembic commands ###
